services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - appnet

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=flaskhit
      - POSTGRES_USER=flaskapi
      - POSTGRES_PASSWORD=fastpass
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - appnet
  
  api:
    build: .
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
      - DATABASE_HOST=db
      - POSTGRES_DB=flaskhit
      - POSTGRES_USER=flaskapi
      - POSTGRES_PASSWORD=fastpass
    networks:
      - appnet
    depends_on:
      - redis
      - db

volumes:
  redis-data:

networks:
  appnet: